language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libssl-dev
before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
after_script:
  - cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash)
